# Generated by Django 5.2.9 on 2025-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_refund_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispute_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
